### ISSUE TITLE
does not flip when a semicolon is not present at the end of a shorthand rule

### ISSUE THREAD

**Issue by probablyup** [cssjanus/cssjanus#81] opened 2019-12-24 03:13 UTC
This does not flip

```css
margin: 0 5px 0 0
```

This does flip

```css
margin: 0 5px 0 0;
```

As tested on **[Demo](https://cssjanus.github.io/#input/margin%3A%200%205px%200%200%0A%0Amargin%3A%200%205px%200%200%3B)**

**Comment by Krinkle** [comment] 2020-08-24 03:19
Hi @probablyup,

Semicolons are indeed be optional in CSS (for the last or only declaration in a rule), and as such CSSJanus should work the same with and wihout it.

However in this case it suspect the reason it seems incorrect is because the example is too short. In real CSS rules, there would be a curly brace after the rule, in which case CSSJanus does flip both with and without semicolon.

This is intended so that CSSJanus knows for sure that there is not other CSS values after it (e.g. 5 space-separated values) are are thus left alone if the input is incomplete or unknown.

```css
/* both flip as expected */

.foo {margin: 0 5px 0 0}
.foo {margin: 0 5px 0 0;}
```

**[Demo](https://cssjanus.github.io/#input/.foo%20%7Bmargin%3A%200%205px%200%200%7D%0A%0A.foo%20%7Bmargin%3A%200%205px%200%200%3B%7D)**

Please let me know if ths partial input was intended and how this might be an issue in practice. Perhaps there's a larger direction that I can support instead.

**Comment by Krinkle** [comment] 2020-09-18 20:54
Based  on https://github.com/styled-components/styled-components/releases/tag/v5.0.0-rc.3, I'm guessing it now passes a full rule and works as expected.

Closing as such. If not, or if you run into anything else, always happy to help!

**Closed by Krinkle** 2020-09-18 20:54 UTC
Labels: Type: Support

**Comment by probablyup** [comment] 2020-09-18 20:58
@Krinkle yes thank you
